#include <stdio.h>

int main(){
	
	int linha = 1;
	
	while(linha <= 1000){
		printf("\n %i : TO COM FOMEEEEEE!!TO COM FOMEEEEEE!!TO COM FOMEEEEEE!!TO COM FOMEEEEEE!!TO COM FOMEEEEEE!!TO COM FOMEEEEEE!!TO COM FOMEEEEEE!!TO COM FOMEEEEEE!!TO COM FOMEEEEEE!!TO COM FOMEEEEEE!!TO COM FOMEEEEEE!!TO COM FOMEEEEEE!!TO COM FOMEEEEEE!!TO COM FOMEEEEEE!!TO COM FOMEEEEEE!!TO COM FOMEEEEEE!!TO COM FOMEEEEEE!!\n", linha);
		
		linha++;
	}
	
	return 0;
}
