// EXP-02: PROGRAMA 2.1 SEMAFORO_3LEDS
void setup()
// ESTA BARRA DUPLA SIGNIFICA QUE OS CARACTERES A SEGUIR SÃO COMENTÁRIOS E O PROGRAMA
//NÃO OS EXECUTA.
{
 pinMode(13,OUTPUT); // DEFINE O PINO 13 COMO OUTPUT, OU SEJA, VARIÁVEL DE SAÍDA.
 pinMode(12,OUTPUT); // IDEM PARA O PINO 12.
 pinMode(11,OUTPUT);
 pinMode(10,OUTPUT); // IDEM PARA O PINO 11.
}
void loop() // COMEÇA AQUI A REPETIÇÃO DOS COMANDOS (ENTRE OS COLCHETES).
{
 digitalWrite(13,HIGH); // COLOCA O PINO 13 EM NÍVEL "ALTO", OU SEJA, 5 V; O LED VERM. ACENDE.
 delay(300); // TEMPO DE ESPERA DE 4 SEGUNDOS.
 digitalWrite(13,LOW); // COLOCA O PINO 13 EM NÍVEL "BAIXO", OU SEJA, 0 V; O LED VERM. APAGA.

 digitalWrite(12,HIGH); // COLOCA O PINO 11 EM NÍVEL "ALTO", OU SEJA, 5 V; O LED VERDE ACENDE.
 delay(300); // TEMPO DE ESPERA DE 4 SEGUNDOS.
 digitalWrite(12,LOW); // COLOCA O PINO 11 EM NÍVEL "BAIXO", OU SEJA, 0 V; O LED VERDE APAGA.

 digitalWrite(11,HIGH); // COLOCA O PINO 12 EM NÍVEL "ALTO", OU SEJA, 5 V; O LED AMAR. ACENDE.
 delay(300); // TEMPO DE ESPERA DE 2 SEGUNDOS.
 digitalWrite(11,LOW); // COLOCA O PINO 12 EM NÍVEL "BAIXO", OU SEJA, 0 V; O LED AMAR. APAGA.
 
 digitalWrite(10,HIGH);
 delay(300);
 digitalWrite(10,LOW); 
 
 digitalWrite(11,HIGH); // COLOCA O PINO 12 EM NÍVEL "ALTO", OU SEJA, 5 V; O LED AMAR. ACENDE.
 delay(300); // TEMPO DE ESPERA DE 2 SEGUNDOS.
 digitalWrite(11,LOW); // COLOCA O PINO 10 EM NÍVEL "ALTO", OU SEJA, 5 V; O LED Branco. ACENDE.

 digitalWrite(12,HIGH); // COLOCA O PINO 11 EM NÍVEL "ALTO", OU SEJA, 5 V; O LED VERDE ACENDE.
 delay(300); // TEMPO DE ESPERA DE 4 SEGUNDOS.
 digitalWrite(12,LOW);

 digitalWrite(13,HIGH); // COLOCA O PINO 13 EM NÍVEL "ALTO", OU SEJA, 5 V; O LED VERM. ACENDE.
 delay(300); // TEMPO DE ESPERA DE 4 SEGUNDOS.
 digitalWrite(13,LOW);
 } 